metadata_bulk_operations:
  s3_bucket_name: <VALUE>
data_import:
  s3_bucket_name: <VALUE>
  error_prefix: <VALUE>
  data_prefix: <VALUE>
  role_arn: <VALUE>
anomaly_detection:
  asset_id: <VALUE>
  input_property_ids:
    - <VALUE>
    - <VALUE>
    - <VALUE>
    - <VALUE>
  result_property_id: <VALUE>
  computation_model_name: <VALUE>
  training:
    data_start_time: <VALUE>
    data_end_time: <VALUE>
    target_sampling_rate: <VALUE>
    labels:
      bucket_name: <VALUE>
      prefix: <VALUE>
    evaluation:
      bucket_name: <VALUE>
      prefix: <VALUE>
      data_start_time: <VALUE>
      data_end_time: <VALUE>
  inference:
    data_delay_offset_minutes: <VALUE>
    data_upload_frequency: <VALUE>
    weekly_operating_window: <VALUE>